### ISSUE TITLE
bindings-posix unbuildable on osx and windows

### ISSUE THREAD

**Issue by phadej** [nilcons/haskell-tz#12]
There are very few use cases (`tzset` and `localtime_r`), so the `bindings-posix` dependency can be dropped. I can do a PR if this is ok.

(obviously right solution would be to fix `bindings-posix`, but that's a way longer path)

**Comment by phadej** [comment]
See https://github.com/jwiegley/bindings-dsl/issues/27

**Comment by phadej** [comment]
Or actually it wasn't https://github.com/jwiegley/bindings-dsl/pull/28

**Comment by phadej** [comment]
... but it seems it's not easy to to build `bindings-posix` on Windows.

**Comment by klao** [comment]
This is fixed by c6e7203. Thanks!
