### ISSUE TITLE
loadTZFromDB and loadSystemTZ differ

### ISSUE THREAD

**Issue by phadej** [nilcons/haskell-tz#14]
If I change `loadSystemTZ` to `loadTZFromDB` in `setupTZ` in `testTZ`, the `checkTimeZone64` tests start to fail at least on mac os x. `checkTimeZone` seem to be ok. Any idea why?

```
  Melbourne correct TimeZone: [Failed]
*** Failed! Exception: 'HUnitFailure (Just (Location {locationFile = "tests/testTZ.hs", locationLine = 78, locationColumn = 13})) "expected: CET\n but got: LMT"' (after 63 tests): 
```

is my mac local locale information invalid?

**Comment by klao** [comment]
I don't have a mac available, but something seems horribly wrong with that test. :)  That `CET` for Melbourne is definitely not a good sign. Investigating...

**Comment by klao** [comment]
I have fixed the "horribly wrong" part. (I shouldn't muck around with `unsafePerformIO`.)

I would be interested in what are your results now. My guess is that you'll still see some failures, at least for Europe/Budapest, but maybe not for all `checkTimeZone64` tests.

But, let me explain the possible reason for the "failures". Indeed, if the tests are passing with `loadSystemTZ`, but are failing with `loadTZFromDB`, it means that your local zone files are _different_ from the ones in `tzdata`. This is quite likely to happen if your system is older. (I don't know how often OS X updates the zone files.)

But, these differences might not be significant, they might just be some cosmetic differences far back in the past. This is probably the case here, judging from the `LMT`, which is the abbreviation used for "before there was an official time zone at that place": Local Mean Time.  You can check if this is the case by changing the lower bound in `checkTimeZone64` from ``-(1 `shiftL` 55)`` to, say 0. Then, you are only testing dates after 1970. If you still get discrepancies, well, that's more troubling...

**Comment by phadej** [comment]
You analysis is true. If I change to `loadTZFromDB` and set the lower bound to `0`, only one test fail:
```hs
  Antarctica Palmer correct TimeZone: [Failed]
*** Failed! Exception: 'HUnitFailure (Just (Location {locationFile = "tests/testTZ.hs", locationLine = 67, locationColumn = 13})) "expected: CLT\n but got: CLST"' (after 1 test): 

  Antarctica Palmer correct LocalTime: [Failed]
*** Failed! Exception: 'HUnitFailure (Just (Location {locationFile = "tests/testTZ.hs", locationLine = 94, locationColumn = 13})) "expected: 2017-05-14 00:00:00\n but got: 2017-05-13 23:00:00"' (after 100 tests and 16 shrinks): 
```

All machines I have access to use CLT for Antarctica/Palmer atm. I really don't know what's in use in Antarctica.
```sh
# Linux ... 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
% TZ=Antarctica/Palmer date
Wed Aug 10 17:26:57 CLT 2016

# Darwin ... 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
% TZ=Antarctica/Palmer date
Wed Aug 10 18:23:43 CLT 2016
```

**Comment by klao** [comment]
:)
Antarctica/Palmer uses Chilean time and it had a change very recently (have DST again): http://mm.icann.org/pipermail/tz-announce/2016-March/000037.html

**Comment by phadej** [comment]
FWIW, i tried to change to `loadTZFromDB`, as `loadSystemTZ` doesn't work on Windows. There aren't `/usr/share/zoneinfo` analogue AFAIK.

The historic information is stored in windows registry, https://msdn.microsoft.com/en-us/library/bb397783(v=vs.110).aspx or https://msdn.microsoft.com/en-us/library/system.timezoneinfo.fromserializedstring(v=vs.110).aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1

So it's *possible* to get `TZ` data from windows, but maybe it's easier for everyone to not export `loadSystemTZ` on Windows at all, and guide to use bundled database. At least until someone really wants to do cross-platform application with extensive timezone support, they can bundle database with it and use `loadFromFile`.

**Comment by klao** [comment]
I have reshuffled the tests and put those that depend on `loadSystemTZ` in a separate file, and disabled it on Windows. With this, I got `stack test` to successfully pass. Do you think there is anything else needed in terms of OS X and Windows compatibility/support? Please let me know!

Also, a small note, you don't need to hand-roll a file-embedding + `parseOlson` solution. The library already supports this in two ways: if you use `Data.Time.Zones.All`, then all of the supported zones will be embedded in your aplication. And, if you only need a few, you can use `includeTZFromDB` from `Data.Time.Zones.TH`.

**Comment by klao** [comment]
I have uploaded a new minor version to Hackage.

**Comment by phadej** [comment]
TIL `Data.Time.Zones.All`, great :+1:

**Comment by phadej** [comment]
I'll check the new version next week. Will reopen if there are still some issues.

**Comment by phadej** [comment]
thanks a lot!
