### ISSUE TITLE
TZ -> TZLabel

### ISSUE THREAD

**Issue by mchaver** [nilcons/haskell-tz#16]
Is there way to include the TZLabel with TZ, get the TZLabel from TZ or get a system's TZLabel? Ideally I would to make a program that finds the local TZ and TZLabel, store the TZLabel and then use that TZLabel later to adjust UTCTime.

**Comment by klao** [comment]
Sorry, I somehow missed this!

The relationship between `TZ` and `TZLabel` is not one-to-one. For example, your system's time zone might or might not correspond to one of the `TZLabel`s. For this reason a `TZ` does not (and really, cannot) contain a `TZLabel`.

But, why don't you just store the TZ itself? I can implement some type classes to make it easier...

**Comment by mchaver** [comment]
@klao Thanks for the response.

I'm still thinking about the best way to handle this. I have a calendar app in GHCJS. A user makes a schedule and each event is stored in `UTCTime`. It would be nice to store their time zone as well because I want to display multiple users' events on a single calendar and optionally show the time zone that the user is in. They could manually pick their time zone but it would be nice to automate it. The timezone label from `getTimeZone` in Data.Time is not unique so that is not useful for storing. I thought TZLabel might be a good option. Any thoughts?

**Comment by mchaver** [comment]
@klao I've come up with a solution for my own code. I will share it here once I get in on github.
