### ISSUE TITLE
Test failure with tzdata 0.2.20201016.0

### ISSUE THREAD

**Issue by felixonmars** [nilcons/haskell-tz#25]
```
Test suite tests: RUNNING...
Main:
  utcTZ is utc: [OK]
  utcTZ zero diff: [OK]
  DB utc is utc: [OK]
  Budapest LocalToUTC: [Failed]
expected: LTUUnique {_ltuResult = 2014-03-22 23:15:15.15 UTC, _ltuZone = CET}
 but got: LTUUnique {_ltuResult = 2014-03-22 22:15:15.15 UTC, _ltuZone = CEST}
  Moscow LocalToUTC: [OK]
  UTC diffForAbbr: [OK]
  Paris diffForAbbr: [OK]

         Test Cases  Total
 Passed  6           6
 Failed  1           1
 Total   7           7
Test suite tests: FAIL
```

**Comment by klao** [comment]
Thank you, I'm aware of this and working on a fix.

**Comment by klao** [comment]
I temporarily reverted the commit that relaxes the version bound on `tzdata` and will only put it back after I have the necessary new code/tests.

**Comment by felixonmars** [comment]
Thanks for the update. I'll wait for a new version :)

**Comment by klao** [comment]
It will take a while to add the necessary functionality in `tz`, so instead I released a new version of `tzdata` which works correctly with the current code: nilcons/haskell-tzdata@cca1193a306d3f145a397e7665a022e1b7a02825 (and deprecated the offending `0.2.20201016.0` version).

This resolves this particular issue and you can unfreeze `tzdata` in Arch. I will open another issue to track the proper solution. 

Thanks again!

**Comment by felixonmars** [comment]
Updated in Arch. Thank you :D
