### ISSUE TITLE
Derive instances

### ISSUE THREAD

**Issue by klao** [nilcons/haskell-tz#3]
Add `Typeable`, `Data` and `Generic` instances for `TZ` and other public types.

**Comment by jystic** [comment]
`Read` would be great too, given you have `Show`, thanks!

**Comment by klao** [comment]
`Show` is good for debugging, mainly.

What would you use a `Read` for?

**Comment by jystic** [comment]
If you get a QuickCheck error on a build bot, it's useful to just be able to paste the Show string in to the editor and use read to recreate the counter example.

Doesn't matter so much for small types, but if you have a complex counter example with lots of types from all over, it's time consuming to track down all the required imports.

**Comment by klao** [comment]
Fair enough; will add that too. Thanks!

**Comment by phadej** [comment]
Won't `Generic` break encapsulation?

I'd add `Lift` for `template-haskell`, so one could `$(runIO $ loadTZFromDB "Europe/Helsinki")`

**Comment by klao** [comment]
@phadej: Yeah, I'll probably leave out `Generic`. Thanks!

For the `template-haskell` though, doing it through `Lift` is inefficient: it will unnecessarily increase the size of your binary. Whereas, with `includeTZFromDB` from `Data.Time.Zones.TH` I am trying to be very careful to just add the compact description of the time zone to the binary. (Of course, the flip side of this is that the `TZ` structure will have to be parsed from the description on first use...)

**Comment by phadej** [comment]
TIL about `includeTZFromDB`. Thanks!
