### ISSUE TITLE
Bump dependencies to fit into Stackage.

### ISSUE THREAD

**Issue by liamoc** [nilcons/haskell-tz#7]
Hi,

Would you be able to adjust your version bounds so that your package can be listed on stackage? The problematic versions are listed here:

https://github.com/fpco/stackage/issues/907

Also, if you are willing to list yourself as the package maintainer for tz on the stackage listing, this would make it possible for your dependencies (like my dixi package) to be on stackage also.

**Comment by klao** [comment]
Thanks for the bug report, and sorry I ignored it for so long!

I see that you've switched from `tz`, so this is probably less relevant for you now. :))  I will add the package to stackage, so you are welcome to switch back to it in the future! ;)

And, thanks again!
